### ISSUE TITLE
Hide physical Xbox controller

### ISSUE THREAD

**Issue by fabsch2003** [r57zone/DualShock4-emulator#1]
It would be nice if you were able to hide the Xbox controller when using DS4 Emulator mode.
Because the physical X1-controller and the virtual DS4 are doing the same inputs and it confuses some other games.
Please implement asap.
All in all it's a great free alternative to tools like reWASD.
F 👍

**Comment by r57zone** [comment]
Hi, do you use DS4Emulator with PS Now? PSNow precedence PS4 controllers over Xbox. You need to start DS4Emulator first and only then PSNow, then the Xbox controller will not manifest itself in any way.

**Comment by fabsch2003** [comment]
I also use it with some other games bc. I like the DS4 button icons more than the XB1 ones. And example MW 2019 just uses the physical XB1 controller instead of the emulated DS4.

**Comment by r57zone** [comment]
Hiding an Xbox controller is quite difficult, unfortunately I don't know how. For some games, there are mods (for example, Resident Evil 4 HD) that replace Xbox icons with PS icons.

**Comment by the-maazu** [comment]
PS Plus is Prioritising Xbox Controller.
[HidHide](this https://github.com/ViGEm/HidHide) works well for this.

Should be included in readme instructions.

![Screenshot 2022-08-30 212957](https://user-images.githubusercontent.com/35778676/187526560-d8d2fff7-b34e-4f5f-9f60-029070f216c6.jpg)
![Screenshot 2022-08-30 212928](https://user-images.githubusercontent.com/35778676/187526578-ae3c4875-2f4d-4a73-977b-008ba4834949.jpg)

**Comment by r57zone** [comment]
Added HidHide to the instruction.
