### ISSUE TITLE
Are there any bugs with L3 Left Thumb keys?

### ISSUE THREAD

**Issue by idgas01** [r57zone/DualShock4-emulator#10]
When I first installed DS4Emulator, I played around with the settings and eventually found settings that I was really happy with.  I had set Ctrl (17) for L3 Left Thumb so I could press the Ctrl key to "listen" in The Last of Us.  And I wasn't sure what I should set R2 Right Trigger to, but I was okay with P (80) to toggle view from over left shoulder to right shoulder.

Then today, I tried some new programs out to see how they compare to DS4Emulator.  I installed GPDSCK (and vJoy) and x360e.  I couldn't get it to work.  It was confusing and anytime I pressed a key, it pressed a different key instead.  So I gave up.

When I went back to DS4Emulator, the Ctrl key no longer worked for Left Thumb to "listen" for enemies.  So I tried changing it to X.  But X wasn't the greatest key.  So I tried R.  R was okay, but then I decided on F.  But the game acted weird.  With F as the key for Left Thumb to "listen" sometimes CTRL worked as L3 Left Thumb.

All I know is I can't get Ctrl (17) to work for L3 anymore.  P does toggle view from left to right shoulder, but only if I point my gun.  If I am not pointing my gun, it pulls up the PlayStation menu instead.  Which is fine.  I just wish I knew what is wrong with the L3 key.  Also, right now, no key seems to be working (that I already used) for L3.  Like X, F, etc. wont' work.  But maybe I can only "listen" in certain parts of the game?

I did uninstall GPDSCK, vJoy, and x360e.  I even uninstalled ViGEmBus and DS4Emulator and installed them again.  Even restarted my computer.

Maybe I am just being dumb.  Maybe nothing is wrong.  It's just acting weird to me and I have no idea how to fix it.  Oh, and I restarted PS Now a lot of times too.

PS - I really like this problem, and I don't have any complaints.  It's easy to use and I appreciate it.  I didn't want to buy a controller and this program does what I want.  Just trying to figure out why I'm having problems with the L3 key now.  I'm tired and half asleep so I will try again tomorrow.

**Comment by r57zone** [comment]
Have you tried returning config to default (from archive)? If you are using a keyboard and mouse, no third-party software is required

**Comment by r57zone** [comment]
Ctrl is numbered 16. I just rechecked, there is no problem with that. Download the latest version and use the config included in the package.

**Comment by idgas01** [comment]
I think that I figured out the problem.  It was my fault.  I was mistaken.  I thought that L3 was for "listening", but it was R2.  So I changed my R2 key to Ctrl (not the L3 button), and it seems to be working now.  Sorry about that.
