### ISSUE TITLE
I found a AutoHotKey script that lets you toggle mouse cursor visibility on/off.

### ISSUE THREAD

**Issue by idgas01** [r57zone/DualShock4-emulator#12]
So this is a six year old script that I found on the internet.  It was really hard to find.  If you press Win + C, it toggles mouse cursor visibility on/off.  Not everyone knows how to create AutoHotKey scripts.  So what you do is you download the AutoHotKey progra installation .zip.  You extract it into a folder.  Then you open the subfolder called Compiler.  Inside the Compiler folder, you create a new .txt document (Notepad) but then you change the extension from .txt to .ahk.  I would also name this new .ahk file HideShowCursor.  Copy the contents of the following code inside that file and then save and close it.  Finally, inside Compiler folder is a Ah2Exe program.  You open that and select the path to the .ahk file you just created.  Then for Base (bin), you select 32-bit or 64-bit.  I always go with 64-bit.  Then click the Convert button.  This will create a new AutoHotKey program executable called HideShowCursor.  Now if you run it and press Win + C, you can toggle mouse cursor visibility.

Here is the code for the script:

```
; Example: Hides the mouse cursor when you press Win+C. To later show the cursor, press Win+C again.
; This script is from www.autohotkey.com/forum/topic6107.html

OnExit, ShowCursor  ; Ensure the cursor is made visible when the script exits.
return

ShowCursor:
SystemCursor(\"On\")
ExitApp

#c::SystemCursor(\"Toggle\")  ; Win+C hotkey to toggle the cursor on and off.

SystemCursor(OnOff=1)   ; INIT = \"I\",\"Init\"; OFF = 0,\"Off\"; TOGGLE = -1,\"T\",\"Toggle\"; ON = others
{
    static AndMask, XorMask, $, h_cursor
        ,c0,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13 ; system cursors
        , b1,b2,b3,b4,b5,b6,b7,b8,b9,b10,b11,b12,b13   ; blank cursors
        , h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,h12,h13   ; handles of default cursors
    if (OnOff = \"Init\" or OnOff = \"I\" or $ = \"\")       ; init when requested or at first call
    {
        $ = h                                          ; active default cursors
        VarSetCapacity( h_cursor,4444, 1 )
        VarSetCapacity( AndMask, 32*4, 0xFF )
        VarSetCapacity( XorMask, 32*4, 0 )
        system_cursors = 32512,32513,32514,32515,32516,32642,32643,32644,32645,32646,32648,32649,32650
        StringSplit c, system_cursors, `,
        Loop %c0%
        {
            h_cursor   := DllCall( \"LoadCursor\", \"uint\",0, \"uint\",c%A_Index% )
            h%A_Index% := DllCall( \"CopyImage\",  \"uint\",h_cursor, \"uint\",2, \"int\",0, \"int\",0, \"uint\",0 )
            b%A_Index% := DllCall(\"CreateCursor\",\"uint\",0, \"int\",0, \"int\",0
                , \"int\",32, \"int\",32, \"uint\",&AndMask, \"uint\",&XorMask )
        }
    }
    if (OnOff = 0 or OnOff = \"Off\" or $ = \"h\" and (OnOff < 0 or OnOff = \"Toggle\" or OnOff = \"T\"))
        $ = b  ; use blank cursors
    else
        $ = h  ; use the saved cursors

    Loop %c0%
    {
        h_cursor := DllCall( \"CopyImage\", \"uint\",%$%%A_Index%, \"uint\",2, \"int\",0, \"int\",0, \"uint\",0 )
        DllCall( \"SetSystemCursor\", \"uint\",h_cursor, \"uint\",c%A_Index% )
    }
}

**Comment by r57zone** [comment]
I have a utility like this to hide the cursor https://github.com/r57zone/Hide-Cursor

**Comment by idgas01** [comment]
Oh, really?  Can you explain your utility more?  Does it use a global hotkey too?  If so, what is it.  Can the global hotkey be changed?  There was a program for auto hiding cursor, but I couldn't use it because it automatically hid the cursor after a period of inactivity and would automatically make the cursor visible if you moved the mouse.  Well I move the moue a lot in PS Now because I am always moving the camera, so that program wouldn't work.  I just want to better understand how your program works and what it does, and what config changes I might be able to make with it.  Please let me know.  Thank you.

**Comment by idgas01** [comment]
Nevermind.  I downloaded it just now and the instruction were inside.  Seems like an "okay" program.  But I think my AHK script that I found is much better.  Why?  Because if I switch to another window and want to use my mouse again, I can't with your program.  The instruction say to press "Enter" to show cursor again, but that only works if you have the HideCursor command prompt window open and in front.  And it doesn't toggle visibility.  It closes the program.  It's too much work closing and restarting the program each time I want to use my mous.  Having additional windows (additional command prompt window on your desktop), and having to alt+tab to the command prompt window to re-enable the mouse cursor is also inconvenient.  With the AHK script above, you don't get an additional program window on your desktop.  It's just a minimized program on your taskbar.  If you need to toggle mouse back on, you just press a hotkey.  You don't need to Alt + Tab to the program window first.  Enter is an okay key if you are in the command prompt window, but for global hotkey purposes it is better to use something like Win + C or some key combination that programs don't often use.  Also your program only has an off switch.  It doesn't have an on switch.  So although I appreciate you having the program, I really think that you should give this new program a try.  I will share it with you so you can test it.  Hold on.

https://www.dropbox.com/s/cwb7tqcombxhb9y/HideShowCursor.exe?dl=0
