### ISSUE TITLE
Give DS4Emulator its own program icon.  (Just an idea.)

### ISSUE THREAD

**Issue by idgas01** [r57zone/DualShock4-emulator#13]
So I decided to pin the DS4Emulator program to my Taskbar for easy access.  I'm going to later search online how to make it open minimized to the Taskbar.  It shouldn't be too hard.  But the DS4Emulator program not having a program icon bothered me.  I will probably search online for a good image.  Maybe an image of a PS4 controller or something.  But anyway, I wanted to show you my temporary icon.

![e2yIhsLzB1](https://user-images.githubusercontent.com/75463665/107441423-d30aca00-6afa-11eb-8ffc-6f0542937bbf.png)

As you can see, the program to the right of PlayStation Now is the DS4Emulator program that is using your GitHub profile image.

I just downloaded your profile image and converted it into an .ico image and then I went to Properties and changed the shortcut icon to the new .ico image.  I'm not very happy with this image, so I will search online for a better controller image later.

If I find some a good image, I will share here on this thread.

IMPORTANT:
Whenever you change a program shortcut icon, you should always go to Run and type this and press enter:
ie4uinit.exe -show
It will refresh the taskbar icons and update them to show the new shortcut icon that you applied.

**Comment by idgas01** [comment]
So this might not be the most elegant image, but I'm pretty happy with it.  I tried a controller but it's too complicated of an image and is wider than it is tall.  Even if I squish it so that it same width and height, it looks bad.  I wanted to directional pad, but all the directional pads that had color were tilted at a weird degree.  I tried the triangle button, but it just didn't look good as this cross button.  So in the end, I settled for this cross button.

![OS9dZMerGh](https://user-images.githubusercontent.com/75463665/107446008-326cd800-6b03-11eb-99a3-ff31f0981b0e.png)

![Cross](https://user-images.githubusercontent.com/75463665/107446013-34cf3200-6b03-11eb-9ef0-a1d46e120b36.png)

**Comment by r57zone** [comment]
I will try to add in the next version

**Comment by r57zone** [comment]
Hi, I added an icon in the latest release https://github.com/r57zone/DualShock4-emulator/releases

**Comment by idgas01** [comment]
Thank you.  I finally updated from version 1.5 to 1.5.1 today.  I didn't test it out yet, but it should work.  I didn't realize until now that you had renamed some of the buttons like Left_Shoulder, Left_Trigger, etc. to simpler L1, L2, etc.  So now that I know, it was easier to update my config files.  And I am glad that you are figuring out the touchpad swipe stuff.  So 1.5.2 is going to be even better!  Thank you!!  I really like this new DS4Emulator program icon, by the way.  It looks very professional.
