### ISSUE TITLE
[Feature Request] Add touchpad swipes using ViGEmBus 1.17?

### ISSUE THREAD

**Issue by idgas01** [r57zone/DualShock4-emulator#14]
![D6WX1HkkPX](https://user-images.githubusercontent.com/75463665/109016302-a965ad00-767b-11eb-92de-93ff36b5647f.gif)

I found out that ViGEmBus 1.17 will allow programs such as yours to implement touchpad swipes.  Could you add this feature?  For more information, please visit this GitHub thread -  https://github.com/ViGEm/ViGEmBus/issues/79

**Comment by r57zone** [comment]
Hi, I will look soon

**Comment by idgas01** [comment]
This is just me venting, doesn't have anything to do with this issue (ticket) that I created.  I had the 7 day trial for PlayStation Now, but I took my time playing The Last of Us so it ended up taking 9 days for me to finish it.  And since I renewed my subscription by one month for $11, I wanted to find and play a few more good games.  But I had a really difficult time finding any games on PlayStation Now that I actually wanted to play, and most of the games were already available on PC.  After digging around, I finally found two games that I wanted to play.  Until Dawn and The Darkness (I had already played the sequel).  Until Dawn, sadly required touchpad swipes, which I think is idiotic.  It wasn't necessary to use touchpad swipes for lighting up a lighter 3-5 times in the game or for flipping pages in a book.  But there was no emulator program in existence that I know of that supports touchpad swipes, except reWASD.  So I gave it a try, and I have to say that it is a trillion times worse than your program.  It was a steaming pile of sh.  In fact, it was so bad, that I found myself in the very beginning of my playthrough of Until Dawn hoping that I could finish the game in a hurry because I couldn't wait to uninstall reWASD and get it off my computer.  Of course later I really liked Until Dawn a lot, so I wasn't that much in a hurry to quit playing the game.  Their program was so bad, that I ended up using DS4Emulator 98% of the time, and just switching controllers to reWASD the few times that I needed to do swipes like when flipping pages and lighting up lighters.  Their program was a real pain in the arse.  Really, if and when you do add swipes, your program which is already a billion times better is going to be a trillion times a trillion times better.  Just be sure to add at least left swipe and right swipe.  Up and down may be important, but if you have to prioritize, start with those two, because those were the two that I had to use in Until Dawn.  My PlayStation subscription will end on March 13, and I'm not going to renew it anytime soon unless I get some crowdfunding donations which will probably never happen.  So I won't be able to use your awesome program for much longer.  But I have to say it is a really sweet program, the best there is, and you should be proud of your masterpiece of an emulator.  It also has a really sweet name.  DS4Emulator.  I like it.  Thanks for all you do and for creating this wonderful software.

**Comment by r57zone** [comment]
I have tried adding this, but so far without success.

**Comment by idgas01** [comment]
Yeah, I'm sure it's not easy to figure out.  Did you try asking the ViGEmBus developer for help or for some helpful documentation?

**Comment by idgas01** [comment]
ViGEm Discord
https://discord.com/invite/EHmru73

ViGEm Forums
https://forums.vigem.org/

**Comment by r57zone** [comment]
It seems the API for working with drivers is not yet ready to the end, I think need to wait a while.

**Comment by r57zone** [comment]
It seems I was able to add support, could you please check if it works correctly? 
[DS4_Test_Touchpad.zip](https://github.com/r57zone/DualShock4-emulator/files/6095310/DS4_Test_Touchpad.zip)

**Comment by idgas01** [comment]
This DS4_Test_Touchpad was difficult to test.

1.) I wanted to test the touchpad swipes in the game 'Until Dawn'.  I wanted to use my previous controls that I had set up from one or two weeks ago.  To save myself time, I copied the [Keys] from my old config file into yours.  But then your config file doesn't support Unicode characters.  By default, all Notepad documents created in Windows 10 supports Unicode characters.  For operating systems older than Windows 10 (Windows XP, 7, Vista, 8.1), it is still easy to create a Notepad document that supports Unicode characters.  You just open up a blank Notepad document.  Type or paste whatever you need.  Then go to 'Save As', and then use the 'Encoding' drop down menu to select 'UTF-8' formatting.  Then you save the document and put this config file in your zip file.  All of your config files should support Unicode characters.

2.) So what I did was I just deleted your config file and copied and pasted my DS4Emulator 1.5 one, but I added the [Main] stuff at the top.  I was expecting it to work, but some of my controls didn't work.  For instance, for R2, I wanted to use 17 or "Ctrl".  But it was still using 1 or "LMB".  Why wouldn't your DS4_Test_Touchpad use my controls that I created?  So it was a real headache and pain to figure out what the new controls were.  I can't play my game if I can't use the controls that I want.

3.) I pressed a bunch of random buttons and was able to pull up my 'Until Dawn' game information window where you can see stuff like - Character Info, Clues, Collectibles, and Butterfly Effects.  I opened up one of the Butterfly Effects because it is like a book with pages.  You can swipe left and right to flip through the pages.  The way you have your touchpad swipes set up is not that great.  Your way requires me to press two buttons very quickly, one after another.  reWASD uses the same ViGEmBus 1.7, but they have one button for each swipe.  So if I wanted to turn a page from right to left using reWASD, I would only need to press one button.  But yours, I have to press Numpad 6 and then Numpad 4 real quick.  But hey, at least it works.  It's better than nothing.  But honestly, I don't use Numpad.  The Logitech Bluetooth keyboard that I have does not have Numpad.  So it would be nice if you combine the two keys per swipe into one key and then let us customize what key we want to use like "1, 2, 3, 4" or some other keys.  Luckily, my laptop had a working Numpad.  But on my other laptop, it had a factory defect where the keyboard doesn't work.  That is why I bought the Logitech Bluetooth keyboard in the first place.  I don't like using multiple keyboards.  So I would prefer a way to not be forced to use Numpad, if possible.

But overall, it is definitely good progress.  You finally figured out how to get the API working.  You just need to improve it and make it so that each swipe only requires one button.  I only tested left and right swipes because the 'Until Dawn' game does not use up and down swipes.  Thank you for working on this!

**Comment by idgas01** [comment]
Nevermind.  I figured out why my old controls didn't work.  You had renamed some stuff like LEFT_SHOULDER was renamed to L1.  That's why I hadn't switched to 1.5.1 yet, because I still needed to learn all of the differences before I could update my config files.  Sorry about that.

**Comment by idgas01** [comment]
1.) By default, all Notepad documents created in Windows 10 supports Unicode characters. For operating systems older than Windows 10 (Windows XP, 7, Vista, 8.1), it is still easy to create a Notepad document that supports Unicode characters. You just open up a blank Notepad document. Type or paste whatever you need. Then go to 'Save As', and then use the 'Encoding' drop down menu to select 'UTF-8' formatting. Then you save the document and put this config file in your zip file. All of your config files should support Unicode characters.

2.) Your touchpad swipe way requires me to press two buttons very quickly, one after another. reWASD uses the same ViGEmBus 1.7, but they have one button for each swipe. So if I wanted to turn a page from right to left using reWASD, I would only need to press one button. But yours, I have to press Numpad 6 and then Numpad 4 real quick. But hey, at least it works. It's better than nothing.  But honestly, I don't use Numpad. The Logitech Bluetooth keyboard that I have does not have Numpad. So it would be nice if you combine the two keys per swipe into one key and then let us customize what key code we want to use like "1, 2, 3, 4" or some other keys. Luckily, my laptop had a working Numpad. But on my other laptop, it had a factory defect where the keyboard doesn't work. That is why I bought the Logitech Bluetooth keyboard in the first place. I don't like using multiple keyboards. So I would prefer a way to not be forced to use Numpad, if possible.

But overall, it is definitely good progress. You finally figured out how to get the API working. You just need to improve it and make it so that each swipe only requires one button. I only tested left and right swipes because the 'Until Dawn' game does not use up and down swipes. Thank you for working on this!

**Comment by r57zone** [comment]
Numpad is used as a temporary solution, I will add changing buttons for touchpad as well as buttons for swipes.

**Comment by r57zone** [comment]
I've added these improvements, it would be great if you could check it out in PS Now. Swipes to "9" and "0" and touchpad movements with "u", "h", "j", "k", "n". 
[DS4_Touchpad_RC1.zip](https://github.com/r57zone/DualShock4-emulator/files/6095980/DS4_Touchpad_RC1.zip)

**Comment by idgas01** [comment]
1.) The TOUCHPAD_SWIPE_LEFT and TOUCHPAD_SWIPE_RIGHT is not very responsive.  Most of the time, it takes me more than 12 tries before it finally responds and swipes left/right.  On reWASD, it always works right away on the first button press.

2.) If I use TOUCHPAD_LEFT and TOUCHPAD_RIGHT together to swipe, it is a little more reliable.  Sometimes it swipes right away.  But a lot of time, it takes around six or so tries.

3.) There should also be a TOUCHPAD_SWIPE_UP and a TOUCHPAD_SWIPE_DOWN.  Don't forget them.

4.) You still did not make the config.ini file support Unicode (UTF-8).  Whenever you finish working on this, please make the default Notepad document config file that is inside the DS4Emulator program zip folder support UTF-8 encoding.

I think that I tested everything.  I could not test TOUCHPAD_UP, TOUCHPAD_DOWN, or TOUCHPAD_CENTER because of the game that I am playing.

**Comment by idgas01** [comment]
PlayStation Now currently has a discount for a one month membership.  It's $1 USD for one month.  Normally it is $9.99 USD.  The offer expires on March 29.  I am going to wait until tomorrow to purchase it because I am tired right now and don't feel like doing any gaming.  So anyway, if you need me to run any tests to help improve your program, let me know.  I am currently using 1.5.1 and haven't updated yet, but I will once I subscribe to PlayStation Now again.  Did you make any improvements to the swipes responsiveness?  I mean, even if you don't, it's better than nothing.  I just hope that you can improve it so that it works on the first press like it does in reWASD.  But I am just happy to have swipes.  So as long as the game doesn't have a time limit for the touchpad swipe, I am good.

**Comment by r57zone** [comment]
Unfortunately not yet, it will be necessary to conduct more research on this topic.

**Comment by r57zone** [comment]
If you buy a subscription in the future, you can check this version, This may have been fixed.
[DS4Emu.A1.zip](https://github.com/r57zone/DualShock4-emulator/files/6216512/DS4Emu.A1.zip)

**Comment by idgas01** [comment]
Okay, I will give it a try sometime in the next 1-12 hours.  Probably within the next 3-4 hours.

**Comment by idgas01** [comment]
The touchpad presses are way more reliable than the touchpad swipes.  Using H+K and K+H to swipe right and left, it always takes less than 6 tries.  Oftentimes between 2-4 tries.  The touchpad swipes are just as bad as in previous versions.  A lot of the time it took 6-10 times.  Very few times it took 2 or 14 tries.  But annoyingly, sometimes it would take as much as 35-45 times for it to work.  It is very unreliable.  I would prefer to use swipes instead of touchpad presses, but because the touchpad presses are way more reliable I think that players should use the touchpad presses instead.  I have no knowledge whatsoever on coding or the API for this program, but maybe you can try experimenting with the speed.  I noticed that when I use touchpad presses like H+K and K+H, it works better if I press them very quickly together without a long pause in between.  So maybe for the touchpad swipes, you should speed things up a little.  Try increasing the speed of the touchpad swipes by 5-10x and see if that helps?

**Comment by r57zone** [comment]
Added new touchpad fixes in latest release

**Comment by idgas01** [comment]
Hey, I haven't tested out the newest version yet.  I haven't used this program in like half a year.  But I'll probably get a PSNow subscription around Black Friday on sale and then use your program to play The Last of Us Part II.  I can't wait to test out the new features and improvements.

I have two ideas (not feature requests) if you are interested.

Idea #1

On the ViGEm GitHub (https://github.com/ViGEm/ViGEmBus), it has this listed:

Known users of ViGEm

A brief listing of projects/companies/vendors known to build upon the powers of ViGEm.

This list is non-exhaustive, if you'd like to see your project included, contact us!

    3dRudder
    Parsec
    GloSC
    UCR
    InputMapper
    Oculus VR, LLC.
    Rainway, Inc
    WiimoteHook
    XJoy
    HP
    DS4Windows
    XOutput
    RdpGamepad
    Touchmote
    Mi-ViGEm
    BetterJoy
    Regame - Cloud Gaming Engine

And anytime I am on Reddit or look at YouTube, people are always suggesting reWASD.  It annoys me to no end when people suggest using that program because even though it lets you change the key configs by using the interface instead of editing a config file, it's a crap program.  I like your program way better.  It's been a long time since I tested reWASD but it costs money, costs a lot of money in fact, and just plain sucks.  People have no idea that your program exists and how great it is.  I almost wish that no one will ever find out about your program.  It can be a well kept secret.  But these clowns have no idea.  I'm surprised you haven't contacted ViGEm and asked them to list your program too.  It's up to you if you want to do that or not.  But maybe it didn't occur to you that you can do that or not, so I wanted to bring it to your attention.


Idea #2

You can add a discussions tab to your GitHub.  So people can use this to ask you general questions instead of submitting issues.  Not many GitHubs have this.  Of all the GitHubs I ever visited, I think that I only saw one or two use this feature.  But it's really nice to have and only takes 10 seconds to set up.

https://docs.github.com/en/discussions

---

So in one month I will test out 1.7.4 or whatever the latest version is and report back to you.  I probably won't test or use the swipes.  But I'm interested in the flashlight recharge and some other things.

**Comment by r57zone** [comment]
Hi, I wrote in Vigem, asked to add, thanks! I have not seen this list before.
Seems discussions to be available by default https://github.com/r57zone/DualShock4-emulator/discussions

**Comment by r57zone** [comment]
It looks like the touchpad works with the gamepad, probably this issue is no longer needed.
