### ISSUE TITLE
[Question] How do I comment out and uncomment text in the config file?

### ISSUE THREAD

**Issue by idgas01** [r57zone/DualShock4-emulator#15]
I want to learn how to comment out 1.) lines of text, 2.) blocks of text, an 3.) parts of a line, but not just the end of the line.

**1.) Lines of text.**

Like this:

```
[DS4]
InvertX=0
InvertY=0

# This line is commented out.
// This line is commented out.
<!-- This line is commented out. -->
```

**2.) Blocks of text.**

Like this:

```
[DS4]
InvertX=0
InvertY=0

# This line (of a block) is commented out.
# This line (of a block) is commented out.
# This line (of a block) is commented out.

// This line (of a block) is commented out.
// This line (of a block) is commented out.
// This line (of a block) is commented out.

<!--
This line (of a block) is commented out.
This line (of a block) is commented out.
This line (of a block) is commented out.
-->
```

**3.) Parts of a line (and not just at the end of the line).**

Like this:

```
[DS4]
<!--This text is commented out.-->InvertX=0<!--This text is commented out.-->
<!--This text is commented out.-->InvertY=0<!--This text is aso commented out.-->

Would be great if it could ignore spaces too, like this:
<!--This text is commented out.--> InvertX=0          <!--This text is commented out.-->
<!--This text is commented out.--> InvertY=0          <!--This text is commented out.-->
```
‎
### Why do I want to do this?

I want to make the config files easier to read and for the config files to have all the information that I need so I don't have to refer to GitHub pages.

This is an explanation of my Last of Us controls (I will need to improve it later by using arrow characters for the dpad):

```
L1 -- LEFT_SHOULDER=2		RMB for "Zoom"
R1 -- RIGHT_SHOULDER=1		LMB for "Fire, Reload Weapon, Use Health"
L2 -- LEFT_TRIGGER=16		Shift for "Sprint"
R2 -- RIGHT_TRIGGER=17		Ctrl for "Listen Mode, Switch Shoulders While Aiming"
L3 -- LEFT_THUMB=70		F for "Focus On Hint/Scene"
R3 -- RIGHT_THUMB=18		Alt for "Flashlight"
O --- CIRCLE=67			C for "Crouch, Previous Menu"
X --- CROSS=32			Space for "Menu Select"
△ --- TRIANGLE=69		E for "Interact"
□ --- SQUARE=81			Q for "Melee, Escaping, Other"
----- SHARE=9			Tab for "Backpack/Crafting"
----- OPTIONS=79		O for "Options"
----- TOUCHPAD=13		Enter (not applicable)
----- DPAD_UP=38 		Up
----- DPAD_LEFT=37		Left
----- DPAD_RIGHT=39		Right
----- DPAD_DOWN=40		Down
```

**1. ) Left side.**

As you can see, the very left side had abbreviations of controls and symbols of controls, such as:
`L1, R1, L2, R2, L3, R3, O, X, △, □` , and soon to be arrow characters for dpad.

It also has `-----`'s because when I use a monospace font in Notepad like consolas, it makes everything neatly aligned.  I may end up switching to a different character instead of `-----`, though.  I might use `______` instead.

‎
**2.) Right side.**

And then on the very far right, I write what the key code stands for and what that button will do.  For instance LEFT_SHOULDER=2...
2 is the key code for RMB, and for this game it is used for "Zoom".

‎
**3.) This is what I want to do on both the Left and Right sides.**

So It would be nice if I could comment out stuff like this and have it ignore all the spaces:
```
<!--L1 __--> LEFT_SHOULDER=2		<!--RMB for "Zoom"-->
<!-______--> DPAD_DOWN=40		<!--Down-->
```

And this would not be as nice, because it doesn't have the aesthetically pleasing spaces:
```
<!--L1 __-->LEFT_SHOULDER=2<!--_____________RMB for "Zoom"-->
<!-______-->DPAD_DOWN=40<!--________________Down-->
```
**4.) Bottom of config file.**

And then I want to add a commented out block on the very bottom of the config file that has every key code, so a person can just look at their config file to know what the key codes are without having to refer to a website page.

‎
**5.) Side note.**

I know that I could put the "explanation of controls" in a separate commented out block.  But I wanted to make it even better than that.  Because I think that it would be nice if the actual config part of the config file had `L1, R1, L2, R2, L3, R3, O, X, △, □` , and soon to be arrow characters for dpad, to the left of the LEFT_SHOULDER=, RIGHT TRIGGER=, CROSS=, etc. to help better orientate users when they are trying to edit their bindings.  When I am changing the config, it helps having those symbols `L1, R1, L2, R2, L3, R3, O, X, △, □` immediately jump out of me.  But also, sometimes when I am in-game, I forgot what I had assigned to `L1, R1, L2, R2, L3, R3, O, X, △, □` and it helps to Alt + Tab to the config file and easily spot where that PS4 button is and what keyboard or mouse button I have assigned to it.

‎
**6.) Conclusion.**

I hope that all the things that I want to do are already possible.  And if not, I hope that DS4Emulator can be tweaked to make them possible.  Thank you for taking the time to read this.

**Comment by r57zone** [comment]
Hi, currently, comments can add  above the lines. In the future, I will probably add a visual editor (with gamepad picture) of settings so that can see and quickly change. The designation is really wrong, I used them from the Xbox, will need to be replaced too. I'll see what else I can do with the comments. 
`
# L1 -- RMB for "Zoom"
LEFT_SHOULDER=2
`

**Comment by idgas01** [comment]
Okay, thank you for the information!

**Comment by idgas01** [comment]
Quick question...

Am I allowed to have line breaks in the config file, without the # symbol?

Example:

```
[Keys]
LEFT_SHOULDER=2

RIGHT_SHOULDER=1

LEFT_TRIGGER=16
RIGHT_TRIGGER=17
```

**Comment by idgas01** [comment]
This is my commented out section for the button codes.

I only proofread this once, so there might still be a mistake or two.  I also haven't tested it yet, so I don't know if the config file will still work with this commented out section at the bottom.

I changed the order of the button codes according to my personal preferences.  And I changed the order of the key names in a few instances (e.g. #188 and #189).

```
#   1 - Mouse Left Button
#   2 - Mouse Right Button
#   4 - Mouse Middle Button
#   5 - Mouse Side Button (1)
#   6 - Mouse Side Button (2)

#  16 - Shift
#  17 - Ctrl
#  18 - Alt
#  32 - Space
#   9 - Tab
#  13 - Enter
#  20 - CapsLock
#   8 - Backspace

#  65 - a A
#  66 - b B
#  67 - c C
#  68 - d D
#  69 - e E
#  70 - f F
#  71 - g G
#  72 - h H
#  73 - i I
#  74 - j J
#  75 - k K
#  76 - l L
#  77 - m M
#  78 - n N
#  79 - o O
#  80 - p P
#  81 - q Q
#  82 - r R
#  83 - s S
#  84 - t T
#  85 - u U
#  86 - v V
#  87 - w W
#  88 - x X
#  89 - y Y
#  90 - z Z

#  49 - 1 !
#  50 - 2 @
#  51 - 3 #
#  52 - 4 $
#  53 - 5 %
#  54 - 6 ^
#  55 - 7 &
#  56 - 8 *
#  57 - 9 (
#  48 - 0 )

# 112 - F1
# 113 - F2
# 114 - F3
# 115 - F4
# 116 - F5
# 117 - F6
# 118 - F7
# 119 - F8
# 120 - F9
# 121 - F10
# 122 - F11
# 123 - F12

# 192 - ~
# 189 - -
# 187 - + =
# 219 - {
# 221 - {
# 188 - < ,
# 190 - > .
# 191 - / ?
#     - \ (there doesn't seem to be a key code for this)
# 186 - ; :
# 222 - ' "

#  96 - Numpad 0
#  97 - Numpad 1
#  98 - Numpad 2
#  99 - Numpad 3
# 100 - Numpad 4
# 101 - Numpad 5
# 102 - Numpad 6
# 103 - Numpad 7
# 104 - Numpad 8
# 105 - Numpad 9
# 109 - Numpad - (minus)
# 107 - Numpad + (plus)
# 111 - Numpad / (divide)
# 106 - Numpad * (multiply)
# 110 - Numpad Del

#  27 - Esc
#  45 - Insert
#  33 - PageUp
#  34 - PageDown
#  35 - End
#  36 - Home
#  46 - Delete
#  44 - PrintScreen
# 145 - ScrollLock
#  91 - LWin
#  92 - RWin
#  93 - Menu

#  37 - Cursor <
#  38 - Cursor ^
#  39 - Cursor >
#  40 - Cursor v
```

**Comment by idgas01** [comment]
I don't know if I did this right, because I haven't test it yet.

```
[Keys]

# L1 --- RMB for "Zoom"
LEFT_SHOULDER=2

# R1 --- LMB for "Fire, Reload Weapon, Use Health"
RIGHT_SHOULDER=1

# L2 --- Shift for "Sprint"
LEFT_TRIGGER=16

# R2 --- Ctrl for "Listen Mode, Switch Shoulders While Aiming"
RIGHT_TRIGGER=17

# L3 --- F for "Focus On Hint/Scene"
LEFT_THUMB=70

# R3 --- Alt for "Flashlight"
RIGHT_THUMB=18

# O ---- C for "Crouch, Previous Menu"
CIRCLE=67

# X ---- Space for "Menu Select"
CROSS=32

# △ ---- E for "Interact"
TRIANGLE=69

# □ ---- Q for "Melee, Escaping, Other"
SQUARE=81

# ------ Tab for "Backpack/Crafting"
SHARE=9

# ------ O for "Options"
OPTIONS=79

# ------ Enter (not applicable for The Last of Us)
TOUCHPAD=13

# ------ Up, Down, Left, Right
DPAD_UP=38
DPAD_DOWN=40
DPAD_LEFT=37
DPAD_RIGHT=39
```

**Comment by r57zone** [comment]
Renamed the names of the buttons and added comments, I hope now it will be more convenient and familiar https://github.com/r57zone/DualShock4-emulator/releases

**Comment by idgas01** [comment]
Thank you.

I like the new program icon.  It is very nice.  I like it better than mine.

I see that you made it so we can customize the key for the exit button.  That's nice.  Thank you.

I didn't see any other changes, except a few # commented areas.  I think that can be helpful, but I already added comments to my config files using the information that you provided.

If you look at https://github.com/r57zone/DualShock4-emulator/issues/11, you can see two things.  1.) For each game, I have # comments for each key.  2.) But not only that, if you scroll down to the very bottom of my thread https://github.com/r57zone/DualShock4-emulator/issues/11, you will see a complete list of all the button key codes.  I made that huge commented out section as a reference guide so I don't have to look on GitHub each time that I want to know the code number for a particular key.

I am not sure why you think the API is not yet completed for touchpad swipes.  reWASD already uses the ViGEmBus touchpad swipes.  The ViGEmBus developer said that ViGEmBus 1.17 already supports touchpad swipes.  But I don't know.  I'm not a developer, so maybe you are right.  Anyway, my PlayStation Now subscription expires soon.  I probably won't renew it for another 1-2 months.  I will just be using your program for five more days to play 'The Darkness' and maybe 'Little Nightmares' and then I won't be able to play anymore.  I will use version 1.5 for now, and I will update at a later time.

Thank you for continuously working on improving your program.  It is definitely the best DS4 emulator program in existence!  Hopefully you will have a look at https://github.com/r57zone/DualShock4-emulator/issues/11 to see some of my ideas.  Thank you.  God Bless!

**Comment by idgas01** [comment]
Oh, I see you already updated https://github.com/r57zone/DualShock4-emulator/issues/11 to make it compatible with 1.15.1.   Thank you.  That's very helpful.
