### ISSUE TITLE
How to use on other programs instead of just PS Now?

### ISSUE THREAD

**Issue by Canescj** [r57zone/DualShock4-emulator#16]
I can't quite figure out how to use it on another window besides PS Now. I tried changing separately both the ActivateInAnyWindow to 1 and changing the ActivateOnlyInWindow name to the window I want to use it in and neither worked. Thanks in advance.

**Comment by r57zone** [comment]
`ActivateOnlyInWindow=PlayStation™Now`
It is necessary to replace the title of the title of the application.

`ActivateInAnyWindow=1`
Or enable for all windows
