### ISSUE TITLE
DS4Emulator Crash

### ISSUE THREAD

**Issue by m4nuele** [r57zone/DualShock4-emulator#17]
Hi,
When i open DS4Emulator after a few second the application crash.

In  the EventVier i find this:

Nome dell'applicazione che ha generato l'errore: DS4Emulator64.exe, versione: 0.0.0.0, timestamp: 0x60462bc9
Nome del modulo che ha generato l'errore: unknown, versione: 0.0.0.0, timestamp: 0x00000000
Codice eccezione: 0xc0000005
Offset errore 0x0000000000000000
ID processo che ha generato l'errore: 0x3f14
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d71a691877036b
Percorso dell'applicazione che ha generato l'errore: C:\TMP\DS4Emulator.1.6.Portable\DS4Emulator64.exe
Percorso del modulo che ha generato l'errore: unknown
ID segnalazione: f9027d19-7767-476b-896f-7480f833ae1e
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: 

Thanks

**Comment by r57zone** [comment]
Hi, could you check this version, will it be the same?
https://github.com/r57zone/DualShock4-emulator/releases/tag/1.5.1

**Comment by m4nuele** [comment]
Hi
Unfortunately this version has the same problem

**Comment by r57zone** [comment]
What is your operating system and bitness (32/64)? 

Is this version not working either? 
https://github.com/r57zone/DualShock4-emulator/releases/tag/1.3.1

Are the libraries installed? 
Visual_CPP_Redistributable_2017
ViGEmBusSetup

**Comment by m4nuele** [comment]
My SO is 64 bit

Version 1.3.1 work only 32bit version, 64 bit Crash

Visual_CPP_Redistributable_2017 yes  is installed
ViGEmBusSetup yes  is installed

Thanks

**Comment by m4nuele** [comment]
Yes I using Windows 10 Enterprise Version 20H2

**Comment by r57zone** [comment]
@m4nuele Are you using any antivirus? Could you check the launch of the application without antivirus? The antivirus seems to be blocking dynamic reading of XInput.

**Comment by r57zone** [comment]
I made a test version with a static library, could you check it out? 
[DS4Emulator.1.7.5.XInput.Static.Portable.zip](https://github.com/r57zone/DualShock4-emulator/files/7620622/DS4Emulator.1.7.5.XInput.Static.Portable.zip)

**Comment by r57zone** [comment]
It looks like the problem has been solved, the necessary description will be fixed and added https://github.com/r57zone/DualShock4-emulator/issues/39
