### ISSUE TITLE
Question: Version of ViGEmBus to compile with?

### ISSUE THREAD

**Issue by pnhofmann** [r57zone/DualShock4-emulator#19]
Hi!

maybe silly question; but what version of ViGEmBus are you using?

Asking, because with this one:
https://github.com/ViGEm/ViGEmBus/blob/master/sdk/include/ViGEm/Common.h
``DS4_REPORT_INIT_EX`` is missing (only ``DS4_REPORT_INIT`` exists) and I get 94 'is not a member of _DS4_REPORT_EX' errors.

I would like to try out some tweaks since for some reason inFAMOUS Second Son does not recognize some touch inputs.

**Comment by r57zone** [comment]
Hi, I modified the library a bit to support touch. 
[Common.zip](https://github.com/r57zone/DualShock4-emulator/files/6472173/Common.zip)

**Comment by pnhofmann** [comment]
Big thanks!

It's not really important and I really dont't want to cause any inconvenience - but you don't have an idea by chance what to do with this one?

<img width="935" alt="Playstationnow" src="https://user-images.githubusercontent.com/30838368/118168248-8eefd400-b41f-11eb-9318-1826b161db52.png">

I hoped I could use bTouchData2 for the second tap, but no luck.

**Comment by r57zone** [comment]
[DS4Emu.A1.zip](https://github.com/r57zone/DualShock4-emulator/files/6474810/DS4Emu.A1.zip)
Try this one, maybe does it help

**Comment by pnhofmann** [comment]
I'm afraid, no. But thanks anyway.
