### ISSUE TITLE
Trigger buttons not working!

### ISSUE THREAD

**Issue by GeeBee44** [r57zone/DualShock4-emulator#2]
Hi, I'm using this program to play on PS4 remote play, till now everything works fine except the trigger buttons. I've attached the controller model below if you need that.

Controller model - https://www.amazon.in/Redgear-Pro-Wireless-Gamepad-Black/dp/B0756CLQWL

**Comment by r57zone** [comment]
Hi, have you tried pressing the bumpers? Have you tested in any game? Try it without a gamepad, in keyboard and mouse mode.
