### ISSUE TITLE
[Feature request] Option to disable mouse emulation

### ISSUE THREAD

**Issue by sylvesterstallownage** [r57zone/DualShock4-emulator#20]
I use ps4 remote play because my ps4 controller is broken.

Add option to disable mouse emulation so it does not get stuck center screen.
and/or add option to disable joy sticks (for fighting games, only dpad and XO/\[] are needed)

Problem:
`[KeyboardMouse]`
`ActivateOnlyInWindow=PlayStation™Now`  <- unknown what to type for "ps4 remote play" window
Mouse gets stuck center screen because of:
`ActivateInAnyWindow=1`  <- changed to 1 so it works for ps4 remote play

Need to alt tab to disable.

**Comment by r57zone** [comment]
Centering the cursor is needed to control the looking in games. 

Do not use sticks unless you need them. I don't think their work gets in the way of the game. You can reassign the buttons to your liking. 

The title of the window is written to ActivateOnlyInWindow. It seems for Playstation Remote Play the name "PS Remote Play" or something like that. If you specify this, then the centering of the cursor will only be in this program and not when switching

**Comment by r57zone** [comment]
Added button "C" (default) to disable centering, added title for second window (PS4 Remote Play) https://github.com/r57zone/DualShock4-emulator/releases
