### ISSUE TITLE
Компиляция

### ISSUE THREAD

**Issue by GFOXSH** [r57zone/DualShock4-emulator#21]
Добрый день! Вы не могли бы, пожалуйста, поделиться полными нормальными include-ами, я не могу никак его собрать, даже не смотря на то, что взял Ваш Common.h из этого обсуждения https://github.com/r57zone/DualShock4-emulator/issues/19 и версию из master-ветки отсюда: https://github.com/ViGEm/ViGEmBus/tree/master/sdk

**Comment by r57zone** [comment]
Добрый вечер, положить исходник с гита в папку app/DS4Windows [ViGEm_libs.zip](https://github.com/r57zone/DualShock4-emulator/files/6540926/ViGEm_libs.zip) и должно сообраться

**Comment by GFOXSH** [comment]
Огромное спасибо! Все собралось!
