### ISSUE TITLE
Keys not working

### ISSUE THREAD

**Issue by Cereeth** [r57zone/DualShock4-emulator#22]
Hi! I installed the vigembus and started the DS4 emulator, then connected to Ps remote play. The strange thing is that the arrows working for navigation and despite the cross button is binded to space, I figured it works with the enter key. Nothing else seems to happen when I try to push any other button, binded, or not binded.

**Comment by r57zone** [comment]
Hi, try pressing Win + R, enter "joy.cpl" and try there. Also need to enable the ActivateInAnyWindow parameter.

**Comment by Cereeth** [comment]
I tried to enable that parameter, did not helped. If i enter joy.cpl, the list is empy for me. I figured that the problem is probably, that the program is closing after a few seconds. When I start it, I see the wireless controller in the list, then it disappears

**Comment by r57zone** [comment]
What operating system do you have? Running DS4Emulator x64 or x86? What is the bitness of the system? Have you installed Visual_CPP_Redistributable_2017_2019?

**Comment by Cereeth** [comment]
My system is x64, i tried to run both, jost to be sure, also in administrator, and win 8 compatibility. I installed Vsiual C++ 2015-2019 redist.

**Comment by r57zone** [comment]
Some people have this problem (crash), I don't know yet what the problem might be.

**Comment by r57zone** [comment]
Similar https://github.com/r57zone/DualShock4-emulator/issues/17

**Comment by r57zone** [comment]
Perhaps the antivirus is blocking access to the XInput library, one user was helped by disabling the antivirus.

**Comment by r57zone** [comment]
I made a test version with a static library, could you check it out? 
[DS4Emulator.1.7.5.XInput.Static.Portable.zip](https://github.com/r57zone/DualShock4-emulator/files/7620622/DS4Emulator.1.7.5.XInput.Static.Portable.zip)

**Comment by r57zone** [comment]
It looks like the problem has been solved, the necessary description will be fixed and added
