### ISSUE TITLE
[Feature request] Deadzone option for sticks

### ISSUE THREAD

**Issue by triatic** [r57zone/DualShock4-emulator#24]
Firstly, thank you so much for the great software! I can play Until Dawn on my PC with an Xbox 360 controller!

The problem is that Until Dawn's story choices are selected with the analogue stick, and my controller selects options without me pressing anything due to the stick being slightly off-centre when not pressed (it is old).

Can you add a deadzone option so that, for instance, the stick only registers when at 25% of maximum?

**Comment by r57zone** [comment]
Hi, I will try to add in future versions, thanks for the suggestion.

**Comment by triatic** [comment]
Great, thanks once again. 👍

**Comment by r57zone** [comment]
Hi, I added support for dead zones. Connect the joystick, run the program, press ALT + F7 in it, write the drift value to the config file (Config.ini parameters DeadZoneLeftStickX, Y...) and restart the program. Please check if it works well for you.

I also please check the touchpad in the game, whether its operation has changed. I have slightly updated the code associated with it. Thanks.

[DS4EmulatorWithDeadZones1.zip](https://github.com/r57zone/DualShock4-emulator/files/7034573/DS4EmulatorWithDeadZones1.zip)

**Comment by triatic** [comment]
Thank you, but this version is not working properly. After the "Until Dawn" title screen, it says:


![image](https://user-images.githubusercontent.com/42704418/130532561-73610518-b53e-447f-9c85-993bdc5ae8d7.png)

The previous version is still working ok.

**Comment by r57zone** [comment]
Try restarting the program

**Comment by triatic** [comment]
I restarted both, controller is not being detected.

**Comment by r57zone** [comment]
Still doesn't work after a reboot? If press Win + R and enter `Joy. cpl`, there will be no gamepads there?

**Comment by triatic** [comment]
It still doesn't work in PS Now, joy.cpl has two entries, my wired Xbox 360 controller and "Wireless Controller"

**Comment by r57zone** [comment]
Added in the latest release
