### ISSUE TITLE
[Feature Request] Extracting gyroscope data via android Phone

### ISSUE THREAD

**Issue by hypostock** [r57zone/DualShock4-emulator#26]
I was wondering if gyroscope support can be added like how cemu does it

https://cemuhook.sshnuke.net/padudpserver.html

**Comment by r57zone** [comment]
Hi, interesting idea, I'll study it.

**Comment by hypostock** [comment]
Thanks. Any updates so far?

**Comment by r57zone** [comment]
I'll try later.

**Comment by r57zone** [comment]
Added in the new version for Android phones https://github.com/r57zone/DualShock4-emulator/releases

**Comment by hypostock** [comment]
ah nice.. i will test this out and let you know as soon as possible...

**Comment by r57zone** [comment]
Added sensitivity changes in the latest release https://github.com/r57zone/DualShock4-emulator/releases
