### ISSUE TITLE
[Feature Request] Add a controller vibration function?

### ISSUE THREAD

**Issue by idgas01** [r57zone/DualShock4-emulator#28]
I don't know if ViGEmBus supports the controller vibration function yet.  I would imagine that it does since it supports other things like touchpad swipes.  I would ask on their GitHub but they are preventing people from reporting bugs, submitting questions, and making feature requests.  They want users to ask on Discord instead, and there is nothing that I hate more than a GitHub repository trying to send me elsewhere or trying or to use a chat room.

I'm not using DS4Emulator right now because I am not subscribed to PlayStation Now.  At least not yet.  I plan to subscribe sometime between now and December 10, 2021.  Most likely around 3-4 weeks from now.  The game that I want to play is The Last of Us Part II.  In this game, you have to shake the controller to recharge the flashlight.  I don't think that it is absolutely necessary to have the flashlight charged, but it is a nice game with many hours of gameplay and it would be better if I could have a charged, working flashlight during that time.  So if your DS4Emulator doesn't support it yet, could you look into adding it?  I hope so.  Thank you.

**Comment by r57zone** [comment]
It is possible that there will be support for the gyroscope appear via the Android phone. Gamepad vibration has been supported since the first version. 
https://github.com/r57zone/DualShock4-emulator/issues/26

**Comment by idgas01** [comment]
I have no idea what a gyroscope is and I'm not using an Android phone.  I'd rather not use a phone for anything.  I'm guessing the phone would act as a controller or something.  I just want to press a key on my keyboard and pressing that key will make the game think that I am shaking my controller (to charge my flashlight).  Can that feature be added?

**Comment by idgas01** [comment]
Thank you.  I was thinking about waiting until November 10 before I subscribe, but there is a tiny chance that I might subscribe before then.  I'm not sure yet.  Can't wait to try it out.
