### ISSUE TITLE
Gyro tilting on buttons

### ISSUE THREAD

**Issue by dewos** [r57zone/DualShock4-emulator#31]
Hello,

It would be nice if you were able to use the "share" button on the Xbox controller  (and not the "Back")  to handle the special cases.

For example:

- HOLDING "SHARE" + D-PAD   = Taps on touchpad (up down left right)
- HOLDING "SHARE" + L-STICK = Tilting left and right (basic gyro)
- ~~BACK = Taps on touchpad (center)~~ -implemented
- ~~HOLDING "SHARE" + L3 OR R3 = Shaking the gamepad~~ - implemented
- ~~HOLDING "SHARE" + R-STICK = Swipes on touchpad (up down left right)~~ - implemented

**Comment by r57zone** [comment]
Added the ability to change buttons for "shake the gamepad" (gyroscope) for the Xbox controller, in the latest version, you can reconfigure it in the configuration file.
https://github.com/r57zone/DualShock4-emulator/releases/

**Comment by ZeptoBST** [comment]
I've made a modified version of the software which includes the ability to send gyro tilting using the dpad. I'll be uploading it soon.

**Comment by ZeptoBST** [comment]
Here it is: https://github.com/ZeptoBST/DualShock4-emulator/releases/tag/Release

**Comment by r57zone** [comment]
@ZeptoBST Have you tested this in games? Does it work well?

**Comment by ZeptoBST** [comment]
I tested with Sly 4 and it worked great.

**Comment by r57zone** [comment]
Okay, when I have time I will add it to this version, thanks a lot!

**Comment by ZeptoBST** [comment]
I replaced the "shake the gamepad" function with the tilting one. It might need some changes if we want both features.

**Comment by r57zone** [comment]
Вращение геймпад на кнопки добавлено благодаря @ZeptoBST 
https://github.com/r57zone/DualShock4-emulator/releases
