### ISSUE TITLE
Inputs from emulator not registering

### ISSUE THREAD

**Issue by thetoileter** [r57zone/DualShock4-emulator#34]
Hi,

I'm using the DS4 emulator version 1.7.4 and my inputs aren't registering and the cursor isn't fixed to the center of the screen as it is supposed to be. The computer can recognise the emulator and so can the PSNow, but any inputs of the emulator are not being registered in-game. 

Is there anything I can do to fix this?

**Comment by r57zone** [comment]
Hi, PSNow launched? 
If you just want to test the program, then change `ActivateInAnyWindow` to `1`.

**Comment by r57zone** [comment]
You've probably solved the problem.
