### ISSUE TITLE
Motion Sensor support?

### ISSUE THREAD

**Issue by absenther** [r57zone/DualShock4-emulator#4]
i'm primarily using this tool as a passthrough for other apps/games that supports DS4 but there is no motion sensor data.

edit: just to clarify, i'm using a DS3 with scptoolkit, i want to get the motion data from the DS3 to the DS4 Emulator.

**Comment by r57zone** [comment]
Most likely there will be no support, the Vigem driver that I use does not support either.

**Comment by r57zone** [comment]
Added gyro support https://github.com/r57zone/DualShock4-emulator/releases
