### ISSUE TITLE
Cursor hide until restart

### ISSUE THREAD

**Issue by dado997** [r57zone/DualShock4-emulator#48]
When HideCursorAfterStart the cursor is hide even after i close the app with ALT + Escape.

**Comment by r57zone** [comment]
Hi, the parameter is set to `HideCursorAfterStart=1`, the cursor is hidden after the program is started, but after closing with ALT + Escape, it is not restored, right?
In this case, it may be worth using some program to hide the cursor and not use this built-in function.

**Comment by dado997** [comment]
Yeah that's the problem. I'll use a program to hide the cursor then, thanks for the tip :), btw would be awesome to fix the issue of the program, just to not have to open other extern programs, thanks anyway, bye
