### ISSUE TITLE
Gyroscope tutorial?

### ISSUE THREAD

**Issue by awsumturtle** [r57zone/DualShock4-emulator#49]
Can't figure out how to use the app, I've tried following instructions and trying different things but to no avail.
Could someone help setting it up? Thanks.

**Comment by r57zone** [comment]
Are incoming connections allowed in the Firewall? Does the phone have a gyroscope?

**Comment by r57zone** [comment]
https://github.com/r57zone/DualShock4-emulator#gyroscope

**Comment by awsumturtle** [comment]
> Are incoming connections allowed in the Firewall? Does the phone have a gyroscope?

Phone has gyro, tried even turning off private firewall and still nothing.
