### ISSUE TITLE
L2 and R2 does not work in Gravity Rush 2, Ace Combat 7 and Bloodborn (and maybe everywhere, I tested just this 3 games)

### ISSUE THREAD

**Issue by Metafalica** [r57zone/DualShock4-emulator#5]
Hello. I tried to use your cool program with ps remote play, but there is something wrong with triggers emulation.
I tried both: keyboard mode and xbox360 mode.
In Ace Combat 7 the fighter jet should get speed boost from L2 or R2 but nothing happens when I hold them pressed.
In Gravity Rush 2 those buttons used for dodging and dashing, but totally not work too.
Can you retest and fix it?

**Comment by r57zone** [comment]
Hello,  could you go to press Windows + R, enter `rundll32 joy.cpl, ShowJoyCPL`
Next, select a wireless controller and try to press the triggers there smoothly. Will the axis change smoothly there?

**Comment by Metafalica** [comment]
Hello. Yes, the bars move smoothly in both xbox360 controller and wireless controller. But For weird reason bars move for different axes: axe Z +- for xbox360 and axes X&Y + for wireless.
![DS4 L2](https://user-images.githubusercontent.com/5286295/101457342-d6dd6d00-394e-11eb-81be-14153708c442.jpg)
![DS4 R2](https://user-images.githubusercontent.com/5286295/101457345-d80e9a00-394e-11eb-9cbd-f48c93e82f12.jpg)
![Xbox 360 L2](https://user-images.githubusercontent.com/5286295/101457347-d80e9a00-394e-11eb-9fef-f504f2756763.jpg)
![Xbox 360 R2](https://user-images.githubusercontent.com/5286295/101457349-d8a73080-394e-11eb-9ae0-1baf1e110cb5.jpg)

**Comment by r57zone** [comment]
Could you try to change the parameter `SwapTriggersShoulders=0` to `SwapTriggersShoulders=1` in the config and try again (with swap L1 and L2, R1 and R2), will the game behave differently?

Do you have the opportunity to check this with other games, races?

**Comment by Metafalica** [comment]
I tried the game with SwapTriggersShoulders=1, but it does not solve the problem.
Yes, bottom triggers started to work, but they do now what upper triggers done before, while upper triggers does not work, so I still can't dash and dodge in Gravity Rush 2.

This is the picture how real DS4 controller reacts on shoulders presses. Notice button 7 has red light? Nothing like that happens in emulated DS4 on my pictures. The bar change, but button isn't pressed.
![real ds4](https://user-images.githubusercontent.com/5286295/101466335-73f1d300-395a-11eb-86a5-560de4d502bc.jpg)

**Comment by r57zone** [comment]
Кажется исправил, попробуй новую версию, должно заработать
It seems to be fixed, try the new version, it should work
https://github.com/r57zone/DualShock4-emulator/releases

**Comment by Metafalica** [comment]
Спасибо, теперь все пашет, как надо.
Thanks, now everything is fine.

Еще не по теме, но было бы круто, чтобы с клавы не сразу степень нажатия 255 слалась, а постепенно наростала и убывала при зажатой клавише (допустим, на +-25 за итерацию). Это чтобы с клавы можно было играть более плавно. Кому нужна средняя степень нажатия, будут то нажимать, то отпускать клавишу.

**Comment by r57zone** [comment]
Подумаю на эту тему, но пока PSNow закрыли и тестировать негде, насколько хорошо это будет работать в играх.

**Comment by r57zone** [comment]
Я сделал тестовую версию, не мог бы попробовать её в игре? Будут ли верно работать эмуляция аналоговых триггеров?
[DS4EmulatorAnalogTriggerTest.zip](https://github.com/r57zone/DualShock4-emulator/files/5659107/DS4EmulatorAnalogTriggerTest.zip)

**Comment by Metafalica** [comment]
Без проблем, проверю - отпишусь.

**Comment by Metafalica** [comment]
Мои субъективные ощущения такие, что все равно сила нажатия нарастает очень быстро. Чуть ли не мгновенно.
В бладборне перс чел может пилой пилить при зажатом триггере. Я отпускал и вновь нажимал клавишу очень быстро, но перс переставал пилить сразу же. Т.е. сила нажатия падала до нуля почти мгновенно, и игра переставала воспринимать ее как зажатие кнопки.
С другой стороны, на триггер же перс и стреляет. Было бы плохо, если ты нажал, а он стрельнет только через пол секунды (к примеру).
Ну а с третьей стороны ничего не сломалось.
В Ace Combat 7 можно ускоряться и лететь на желаемой (не максимальной) скорости жамкая кнопку, но там сама игра добавляет плавность.
Возможно вынести значение в конфиг, и каждый настроит, как захочет. А, возможно, даже два значения - для зажатия и отпускания триггера.
Посмотрел как заполняется шкала в окошке от **rundll32 joy.cpl, ShowJoyCPL** - почти мгновенно тоже.

**Comment by r57zone** [comment]
Я добавил изменение шага в конфиг, вместо 25 можно поставить 5, 1 или 0.1. Можно попробовать изменить "AnalogTriggerStep".
[DS4EmulatorAnalogTriggerTest2.zip](https://github.com/r57zone/DualShock4-emulator/files/5659358/DS4EmulatorAnalogTriggerTest2.zip)

**Comment by Metafalica** [comment]
При 5, вроде, самое то. В бладборне теперь перс пилит, даже если жамкать клавишу, а не держать. Но нажимать все-таки надо быстро, иначе перестанет, но это и ожидалось. Стреляет с приемлемой задержкой (или без нее).
В гравити раш 2 тоже все норм при 5, кувыркается и скользит без проблем.
Думаю, те у кого нет геймпада, будут довольны аналоговыми триггерами.

**Comment by r57zone** [comment]
Опубликовал для всех https://github.com/r57zone/DualShock4-emulator/releases

Спасибо за предложение улучшений и тестирование.

**Comment by Metafalica** [comment]
Нет проблем. Тебе спасибо за оперативное исправление и респект за ПРОСТУЮ прогу. Просто мечта - запустил, и она работает без тонны окошек с настройками.

**Comment by Metafalica** [comment]
А кроме ViGEm что-то нужно, чтобы компилить твою прогу? Мне туда вещи посложнее надо добавить, чтобы пройти гравити раш 2 (ведение пальцем сверху вниз и наоборот по сенсорной панели).
Качнул исходники, качнул ViGEm, положил содержимое его папки include рядом с твоим главным cpp
![изображение](https://user-images.githubusercontent.com/5286295/101505133-73266480-398d-11eb-8d27-dda11e4c5cf4.png)
Однако при компиляции дофигища ошибок.
![изображение](https://user-images.githubusercontent.com/5286295/101505677-0a8bb780-398e-11eb-824b-7571e5dfae5e.png)

А еще я хочу добавить поддержку нажатия кнопки Ps на геймпаде, а то из игры не выйти.
