### ISSUE TITLE
Shake button issue

### ISSUE THREAD

**Issue by Alc-chaya** [r57zone/DualShock4-emulator#50]
Some games need pressing RB and shaking at at same time.So are the any way to chage the button of shake?

**Comment by r57zone** [comment]
Hi, not yet, but I'll try to add.

**Comment by r57zone** [comment]
As a temporary solution, you can use the AntiMicro program by simply binding the "T" keyboard button to the desired gamepad button.

**Comment by Alc-chaya** [comment]
Thank you!It's a good mathod but It's a pity that that way can't be used on RPCS3!Anyway thank you for your advise

**Comment by Alc-chaya** [comment]
And select+RT may be a good button for the game I'm playing No More Heroes Red Zone) But for other game there will be diffient issue.

**Comment by r57zone** [comment]
Added the ability to change buttons for "shake the gamepad" (gyroscope) for the Xbox controller, in the latest version, you can reconfigure it in the configuration file.
https://github.com/r57zone/DualShock4-emulator/releases/
