### ISSUE TITLE
PlayStation Plus app compatible

### ISSUE THREAD

**Issue by vincent-deprato** [r57zone/DualShock4-emulator#52]
Since the new PlayStation Plus app, the PS Now app no ​​longer exists.
You have to modify the Config.ini file and change like this:

ActivateOnlyInWindow=PlayStation Plus

**Comment by r57zone** [comment]
Ok, thanks

**Comment by r57zone** [comment]
I have updated the archive, could you please check the full screen mode with keys ALT + F10?
