### ISSUE TITLE
Support for the new PlayStation Plus app

### ISSUE THREAD

**Issue by Dante-IS74** [r57zone/DualShock4-emulator#54]
(en) Hello!  
The emulator worked great with the PlayStation Now app.  After merging PlayStation Now and PlayStation Plus together, in the new application, the emulator stopped working with my Xbox 360 wireless controller. In the application menu, the controller seems to work, but there is no reaction in games. 
Tell me, please, what can be done?

(ru) Привет! 
Эмулятор отлично работал с приложением PlayStation Now. После слияния воедино PlayStation Now и PlayStation Plus, в новом приложении эмулятор перестал работать с моим беспроводным геймпадом Xbox 360. В меню приложения геймпад вроде как работает, но в играх нет реакции. 
Подскажите, пожалуйста, что можно сделать?

**Comment by r57zone** [comment]
Привет, а если запускать с отключенным геймпадом курсор центрируется по центру? Есть возможно проверить работу без геймпада совсем?

**Comment by Dante-IS74** [comment]
Да, без геймпада курсор мыши центрируется.

**Comment by r57zone** [comment]
Да, драйвер Vigem требуется для работы программы, можно переустановить его.

**Comment by Dante-IS74** [comment]
Да. Причина была именно в драйвер V-gem. Переустановить и всё заработало. Спасибо большое за помощь! Программа реально работает и в ней есть всё, что нужно!
