### ISSUE TITLE
Hello any work around to make it works on PsNOW via Lutris in Linux (Wine with Windows XP Prefix) 

### ISSUE THREAD

**Issue by jackbrownhf** [r57zone/DualShock4-emulator#6]
As in the object, I'm running Ps Now on Linux via Lutris, and it works just fine, the only problem that Lutris uses a Windows XP prefix to run PS Now and I can't make it work your useful DS touch-pad emulator.

**Comment by r57zone** [comment]
My program also uses the Vigem driver, it probably won't work in Wine at all.
