### ISSUE TITLE
Motion Emulation with keyboard

### ISSUE THREAD

**Issue by SpaceFrags** [r57zone/DualShock4-emulator#7]
Is it possible to emulate the motion controls of a DS4 controller using the keyboard?

**Comment by r57zone** [comment]
Unfortunately no, motion is not supported.

**Comment by SpaceFrags** [comment]
Understood, but is it something too difficult to program? I mean, I have no idea.

**Comment by r57zone** [comment]
No idea how this can be implemented

**Comment by SpaceFrags** [comment]
ok ok, Thank you for the fast reply!

**Comment by r57zone** [comment]
Added gyro shaking on keyboard https://github.com/r57zone/DualShock4-emulator/releases
