### ISSUE TITLE
Having trouble compiling

### ISSUE THREAD

**Issue by Sqlava** [r57zone/DualShock4-emulator#80]
I'm trying to compile a debug version to test some changes with. I had to do a lot of fighting with Visual Studio to end up with:

`
Error LNK2038 mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in DS4Emulator.obj --- DS4Emulator --- [User Directories]\DualShock4-emulator\DualShock4-emulator\Source\ViGEmClient.lib(ViGEmClient.obj)
`

The problem I have is that I cannot change 'StaticDebug' to 'StaticRlease' in the DS4Emulator solution because it causes several errors concerning debug symbols. I'm assuming the ViGEmClient.lib file that came with the source code was compiled as a release which is causing the problem with making a debug build.

Is there a lib file available that was compiled as a debug version with the 'RuntimeLibrary' value 'MTd_StaticDebug'? If there is no other solution to this would I be forced to compile the ViGEm source?

**Comment by r57zone** [comment]
[debug.zip](https://github.com/r57zone/DualShock4-emulator/files/14235887/debug.zip)
ViGEm lib sources - https://github.com/nefarius/ViGEmClient/tree/master

**Comment by alwk** [comment]
Did you succeed?

**Comment by r57zone** [comment]
Did you succeed?
