### ISSUE TITLE
Sorces Code

### ISSUE THREAD

**Issue by achille12344** [r57zone/DualShock4-emulator#88]
error sorce code Client.h

**Comment by r57zone** [comment]
https://github.com/r57zone/DualShock4-emulator/tree/master/Source/ViGEm
Unzip these files:
https://github.com/ViGEm/ViGEmClient/tree/master/include/ViGEm

Ex functions added to Common.h

**Comment by achille12344** [comment]
![Screenshot 2024-05-22 214349](https://github.com/r57zone/DualShock4-emulator/assets/151840006/643df4b8-7a16-4d4c-bbbc-8e96d8197029)

**Comment by achille12344** [comment]
![Screenshot 2024-05-22 214518](https://github.com/r57zone/DualShock4-emulator/assets/151840006/939d873d-3a78-4ad2-a8f0-531a8c3199ae)

**Comment by achille12344** [comment]
![Screenshot 2024-05-22 214905](https://github.com/r57zone/DualShock4-emulator/assets/151840006/cec2c386-0150-4b9c-83dd-83525804eeb7)

**Comment by achille12344** [comment]
![Screenshot 2024-05-22 215011](https://github.com/r57zone/DualShock4-emulator/assets/151840006/01e2584d-08ea-4b9b-ae23-d8f42d3e6dcc)

**Comment by achille12344** [comment]
![Screenshot 2024-05-22 215325](https://github.com/r57zone/DualShock4-emulator/assets/151840006/3b373813-de27-470b-976b-5c0aea362452)

**Comment by achille12344** [comment]
You can post me here your complete copy of the source thanks

**Comment by r57zone** [comment]
Replace Common.h with this one - tophttps://github.com/r57zone/DualShock4-emulator/blob/master/Source/ViGEm/Common.h

**Comment by achille12344** [comment]
https://filetransfer.io/data-package/dteMlTqo#link

**Comment by achille12344** [comment]
brother or tried to copy the file from getting the same error

**Comment by r57zone** [comment]
[FullSource.zip](https://github.com/r57zone/DualShock4-emulator/files/15413343/FullSource.zip)

**Comment by r57zone** [comment]
Send a screenshot

**Comment by achille12344** [comment]
![Screenshot 2024-05-23 101911](https://github.com/r57zone/DualShock4-emulator/assets/151840006/f35b7963-206e-4166-829e-4f5662e6a732)

**Comment by achille12344** [comment]
You know how to program in python brother

**Comment by achille12344** [comment]
The gamepad model = VG.VDS4Gamepad () works very well

**Comment by achille12344** [comment]
If you want you pass the Source Mouse and Keyboard

**Comment by achille12344** [comment]
![Screenshot 2024-05-23 104053](https://github.com/r57zone/DualShock4-emulator/assets/151840006/b4da9f69-7f04-43a9-b51f-e634a8d88da4)

**Comment by achille12344** [comment]
Makes and mouse buttons mapping only

**Comment by achille12344** [comment]
We want to work together brother

**Comment by r57zone** [comment]
Have you changed tools and sdk to yours in the project settings? Visual Studio gives a lot of irrelevant errors
https://github.com/r57zone/DSAdvance#building

**Comment by r57zone** [comment]
Python is not suitable for working with vigem (creating virtual gamepads), there are no plans to create an interface yet. If you want you can create one for the config files.
