### ISSUE TITLE
How do I shake the controller to recharge my flashlight?

### ISSUE THREAD

**Issue by idgas01** [r57zone/DualShock4-emulator#9]
I never played a PlayStation game before, so I am not familiar with controllers at all.  In The Last of Us, I am supposed to shake the controller or something to recharge the flashlight.  But I don't know how to do that.  I found a forum thread that said something about six-axis, whatever that means.  Is there a way to do this in DualShock4 Emulator?  And if not, can you implement that feature in the near future?  Thank you.

**Comment by r57zone** [comment]
Hi, unfortunately this feature is not supported. In Last of Us, this feature is not very important and you can complete the game without it.
